all: HashTable.class HashArray.class DataItem.class
HashTable.class: HashTable.java
	javac HashTable.java
HashArray.class: HashArray.java
	javac HashArray.java
DataItem.class: DataItem.java
	javac DataItem.java